name: pbl5_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0-200.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  http: ^1.2.0
  flutter_gen_runner: ^5.13.0+1
  flutter_svg: ^2.2.4

  #talker & logger
  talker_flutter: 4.5.4
  talker_bloc_logger: ^4.1.3
  talker_dio_logger: ^4.1.3
  go_router: ^17.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_vlc_player: ^7.4.4
  equatable: ^2.0.8
  flutter_screenutil: ^5.9.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  injectable_generator: ^2.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter/Inter-VariableFont_opsz,wght.ttf
    - family: Public_Sans
      fonts:
        - asset: assets/fonts/Public_Sans/PublicSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Public_Sans/PublicSans-VariableFont_wght.ttf

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml